language: cpp
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-4.0
#      - libclang-common-4.0-dev
#      - libclang-4.0-dev
#      - libclang1-4.0
#      - libclang1-4.0-dbg
#      - libllvm-4.0-ocaml-dev
#      - libllvm4.0
#      - libllvm4.0-dbg
#      - lldb-4.0 llvm-4.0
#      - llvm-4.0-dev
#      - llvm-4.0-runtime
#      - clang-format-4.0
#      - python-clang-4.0
#      - libfuzzer-4.0-dev
#      - cmake
      - sl

before_script:
  - export CC=/usr/bin/clang-4.0
  - export CXX=/usr/bin/clang++-4.0

script:
  - ls -lah
  - echo CC
  - echo CXX
  - /usr/games/sl
